# Generated by Django 5.2.7 on 2025-11-13 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_clie', models.CharField(max_length=100)),
                ('apellido_clie', models.CharField(max_length=100)),
                ('C_E_clie', models.CharField(max_length=100)),
                ('tel_clie', models.CharField(max_length=20)),
                ('direc_clie', models.TextField()),
                ('fech_compra', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_empl', models.CharField(max_length=255)),
                ('apellido_empl', models.CharField(max_length=255)),
                ('puesto_empl', models.CharField(max_length=255)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fech_ingreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_prov', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_prov', models.CharField(max_length=255)),
                ('contacto_prov', models.CharField(max_length=255)),
                ('tel_prov', models.CharField(max_length=50)),
                ('C_E_prov', models.CharField(max_length=255)),
                ('direc_prov', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prod', models.CharField(max_length=100)),
                ('desc_prod', models.TextField(blank=True, null=True)),
                ('precio_unidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('fech_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_prov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='app_Delrio.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fech_venta', models.DateTimeField(auto_now_add=True)),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=50)),
                ('id_clie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='app_Delrio.cliente')),
                ('id_empl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='app_Delrio.empleado')),
                ('id_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='app_Delrio.producto')),
            ],
        ),
    ]
